CREATE TABLE YELP_USER 
(YELPING_SINCE DATE, 
FUNNY_VOTES NUMBER,
USEFUL_VOTES NUMBER,
COOL_VOTES NUMBER,
TOTAL_VOTES NUMBER,
REVIEW_COUNT INTEGER,
FRIENDS_COUNT INTEGER,
NAME VARCHAR2(50),
USER_ID VARCHAR2(30) PRIMARY KEY,
FANS NUMBER,
AVERAGE_STARS FLOAT
);
CREATE TABLE FRIENDS
(USER_ID VARCHAR2(30) NOT NULL,
FRIEND_ID VARCHAR2(30) NOT NULL,
FOREIGN KEY(USER_ID) REFERENCES YELP_USER(USER_ID),
PRIMARY KEY(USER_ID,FRIEND_ID)
);
CREATE TABLE BUSINESS 
(BUSINESS_ID VARCHAR(50) PRIMARY KEY,
ADDRESS VARCHAR(250),
OPEN INTEGER,
CITY VARCHAR(30),
STATE VARCHAR(3),
LATITUDE FLOAT,
LONGITUDE FLOAT,
REVIEW_COUNT INTEGER,
BUSINESS_NAME VARCHAR(100),
STARS NUMBER(5,3)
);
CREATE TABLE BUS_MAINCATEGORY
(CATEGORY_NAME VARCHAR(50) PRIMARY KEY
);
CREATE TABLE BUSINESS_HOURS
(BUSINESS_ID VARCHAR(50),
WORK_DAY VARCHAR(10),
CLOSE_TIME FLOAT,
OPEN_TIME FLOAT,
FOREIGN KEY(BUSINESS_ID) REFERENCES BUSINESS(BUSINESS_ID)
ON DELETE CASCADE
);
CREATE TABLE BUSINESS_CATEGORY
(CATEGORY_NAME VARCHAR(50),
BUSINESS_ID VARCHAR(50),
PRIMARY KEY(BUSINESS_ID,CATEGORY_NAME),
FOREIGN KEY(CATEGORY_NAME) REFERENCES BUS_MAINCATEGORY(CATEGORY_NAME),
FOREIGN KEY(BUSINESS_ID) REFERENCES BUSINESS(BUSINESS_ID)
ON DELETE CASCADE
);
CREATE TABLE BUSINESS_SUB_CATEGORY
(CATEGORY_NAME VARCHAR(50),
BUSINESS_ID VARCHAR(50),
PRIMARY KEY(BUSINESS_ID,CATEGORY_NAME),
FOREIGN KEY(BUSINESS_ID) REFERENCES BUSINESS(BUSINESS_ID)
ON DELETE CASCADE
);
CREATE TABLE BUSINESS_ATTRIBUTES
(ATTRIBUTE_NAME VARCHAR(255),
BUSINESS_ID VARCHAR(50),
PRIMARY KEY(BUSINESS_ID,ATTRIBUTE_NAME ),
FOREIGN KEY(BUSINESS_ID) REFERENCES BUSINESS(BUSINESS_ID)
ON DELETE CASCADE
);
CREATE TABLE REVIEWS
(FUNNY_VOTES NUMBER,
USEFUL_VOTES NUMBER,
COOL_VOTES NUMBER,
TOTAL_VOTES NUMBER,
USER_ID VARCHAR2(30) NOT NULL,
REVIEW_ID VARCHAR(50) PRIMARY KEY,
STARS INTEGER,
REVIEW_DATE DATE,
TEXT CLOB,
BUSINESS_ID VARCHAR(50) NOT NULL,
FOREIGN KEY(USER_ID) REFERENCES YELP_USER(USER_ID),
FOREIGN KEY(BUSINESS_ID) REFERENCES BUSINESS(BUSINESS_ID)
ON DELETE CASCADE
);
CREATE TABLE CHECKIN
(BUSINESS_ID VARCHAR(50) NOT NULL,
WORK_DAY INTEGER,
FROM_HR INTEGER,
TO_HR INTEGER,
NUMBER_OF_CHECKINS INTEGER,
FOREIGN KEY(BUSINESS_ID) REFERENCES BUSINESS(BUSINESS_ID)
ON DELETE CASCADE
);

