DROP INDEX MAINCATEGORY;
DROP INDEX SUBCATEGORY;
DROP INDEX USER_MEMBERSINCE;
DROP INDEX USER_REVIEWCOUNT;
DROP INDEX USER_FRIENDS;
DROP INDEX USER_STARS;
DROP INDEX CHECKIN_DATE;
DROP INDEX CHECKIN_STAR;
DROP INDEX CHECKIN_VOTE;
DROP INDEX CHECKIN_COUNT;
DROP INDEX REVIEW_DATE;
DROP INDEX REVIEW_STAR;
DROP INDEX REVIEW_VOTE;


