DROP TABLE CHECKIN;
DROP TABLE REVIEWS;
DROP TABLE BUSINESS_ATTRIBUTES;
DROP TABLE BUSINESS_SUB_CATEGORY;
DROP TABLE BUSINESS_CATEGORY;
DROP TABLE BUSINESS_HOURS;
DROP TABLE BUSINESS;
DROP TABLE BUS_MAINCATEGORY;
DROP TABLE FRIENDS;
DROP TABLE YELP_USER;

